version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps/npm):"
    target-branch: "development"
    labels:
      - "dependencies"
      - "pkg-npm"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps/actions):"
    labels:
      - "dependencies"
      - "pkg-gh-actions"
    target-branch: "development"
